[[Download]]
== Download and Install

=== Download

Download the following software

. **JDK:** Download and install JDK from http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
. **Eclipse:** Download Eclipse from http://www.eclipse.org/downloads/eclipse-packages/, pick "`Eclipse IDE for Java Developers`" and unzip.
. **Forge:** Download Forge 1.7.10 from
  http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.4.1558-1.7.10/forge-1.7.10-10.13.4.1558-1.7.10-src.zip

=== Mac or Windows

Follow the instructions for Mac or Windows as explained below.

==== Mac

Make sure all the software lised in <<Download>> is downloaded.

. In Finder, go to Applications, Utilities, double click on Terminal
. Change directory to Desktop as `cd Desktop`
. Make a new directory by giving the command `mkdir forge`
. Change to the directory `cd forge`
. Unzip the downloaded Forge 1.7.10 zip file as `unzip ~/Downloads/forge-1.7.10-10.13.4.1558-1.7.10-src.zip`
. Give the command `./gradlew setupDecompWorkspace eclipse`. The output should show `BUILD SUCCESSFUL`.

==== Windows

Make sure all the software lised in <<Download>> is downloaded.

. Open a Command Prompt as explained at http://windows.microsoft.com/en-us/windows-vista/open-a-command-prompt-window
. Change directory to Desktop as `cd Desktop`
. Make a new directory by giving the command `mkdir forge`
. Change to the directory `cd forge`
. In File Explorer, double click on the Forge 1.7.10 zip file downloaded earlier and extract all the contents in this newly created directory.
. In Command Prompt, give the command `gradlew setupDecompWorkspace eclipse`. The output should show `BUILD SUCCESSFUL`.

A detailed video with complete installation steps on Mac is given below:

video::0F7Bhswtd_w[youtube]

Lastly, replace the `src` folder in the `forge-1.7.10-10.13.4.1558-1.7.10-src` folder with the `src` folder from this repository.

=== Verify

This is a very important step as this will confirm that you can actually start modding.

. Open up Eclipse
. In the "`Eclipse Launcher`" window, click on `Browse...`, choose the location of `eclipse` directory in the unzipped forge directory
. Click on "`OK`"
. In the Eclipse window, you should see a "`Minecraft`" folder and be able to expand it. There should be no red exclamation marks next to it.

== Using the Catapult

. Click on the green play button at the top of Eclipse to launch Minecraft
. In the game, open your inventory by pressing `E`
. Click on the compass at the top-right to enter search mode
. Search for `Spawn Catapult`
. Press `T` to open your chat window
. Right click on the ground while holding the `Spawn Catapult` to create a catapult
. Use the command `/catapult <angle> <power>` to set the angle and power of the cow to be launched
. Right click on the catapult to launch a cow